# Service 
apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.fullname }}
spec:  
  selector: 
    name: {{ .Values.fullname }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.targetport }}
  type: NodePort